### ISSUE TITLE
Transformer In Paper

### ISSUE THREAD

**Issue by Litoda** [Zhiyuan-R/Tiger-Diffusion#6]
Hello Sir,

Your work is impressive. Could you provide more details about the transformer you used? From what I've read, it appears to be an extension of a classical Transformer rather than the Point Transformer or V2 that you mentioned in the related work. 
If not, could you explain why you chose not to use Point Transformer v1/v2? Perhaps they are not well-suited for the latent space?"

Thank you!!!

**Comment by Zhiyuan-R** [comment]
Hi! First of all, thank you for your interest in our work. The primary difference from Point Transformer v1/v2 lies in our design of position encoding and the use of a latent input space instead of a point cloud. We chose not to use Point Transformer v1/v2 mainly due to concerns regarding performance and efficiency. 
Another way to understand this design difference is to compare it to how Stable Diffusion, which is trained in latent space, differs from traditional DDPM models that operate in pixel space.

**Comment by Litoda** [comment]
Many thanks!!!
